version: "3.9"
services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: paper-rock-scissors
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 
 
  postgres:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    expose:
      - "8080"
      - "5432"
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
      - "8080:8080"
    volumes:
      - data:/var/lib/postgresql/data

  nakama:
    build: .
    depends_on:
      - postgres
      - mariadb
      - redis
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address postgres:localdb@postgres:5432/nakama        
    expose:
      - "7349"
      - "7350"
      - "7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
    links:
      - "postgres:db"
    environment:
      - HOST=http://127.0.0.1:7350/
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
      - "8090:8090"
      - "9001-9010:9001-9010/udp"
      - "9001-9010:9001-9010/tcp"
    restart: unless-stopped
    volumes:
      - "C:/Users/fucherng1375/Desktop/Build/TestNakama/DedicatedServer:/mnt/c/DedicatedServer"
  
volumes:
  mariadb_data:
  data:
  redis_data: