version: "3.9"

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      urlBase_weather: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/
      APIKey_VisualCrossing: STVZES2L4LTQ865S7VM2QXAX8
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb

volumes:
  mariadb_data:
  redis_data:
